### ISSUE TITLE
0.16.0 Release Plan

### ISSUE THREAD

**Issue by jorisroovers** [jorisroovers/gitlint#170]
I just [released 0.15.0](https://github.com/jorisroovers/gitlint/releases/tag/v0.15.0) 🎉 Thanks again to everyone contributing!

This issue will be used to track any overarching discussion and work related to `0.16.0`.

# **Scope**

**As always, everything discussed in this issue is subject to sudden change at my sole discretion. No promises or hard commitments :-)**

All related issues will be tagged with the [0.16.0 Milestone](https://github.com/jorisroovers/gitlint/milestone/3).

Here's a few things I've been thinking about (most don't have an associated issue) as potential areas to work on next.

- [ ]  Consider moving gitlint under PyCQA. Still not sure at this point (#134)
- [ ]  Add `--commit` flag: #141
- [ ]  Don't have both `requirements.txt` and dependencies in `setup.py`, deduplicate
- [ ]  User-defined `OutputFormatter` classes to allow users to specify the format of the output. Would allow us to easily implement #45 and #53.
    - `OutputFormatter` classes would just be found in the `--extra-path`
- [ ]  `GitContext.config(name, default=None, use_cache=True)` method for easy access to git config (that is also cached). Optionally also provide a mechanism for easy fallback. E.g. `default` can be a string and/or a lambda that implements more complex logic like returning from environment config.
- [ ]  New Rule: ConfigRule: `git config` commands
    - This can just be implemented as a commit rule that just runs a `_git` command (or `GitContext.config` - see above) to pull the value and then compare it to a given regex. By using named rules, users can implement multiple of such rules.
- [ ]  Respect git config `core.editor` for commit msg editing instead of only falling back to `vim` if `$EDITOR` isn't set
- [ ]  gitlint github action
- [ ]  Attempt to fix coveralls.io integration with Github Actions (see `[master`/.github/workflows/checks.yml#L51-L60](https://github.com/jorisroovers/gitlint/blob/master/.github/workflows/checks.yml#L51-L60))
- [ ]  Windows: work a bit on fixing existing issues
- [ ]  Move to Poetry for packaging/building?
- [ ]  Unit Tests: fix running on Windows, try again :-)

# **Timeline**

As always, no specific timeline, but probably in the new year (2021).

**Comment by gsemet** [comment]
Can you release and intermediate version please?

**Comment by jorisroovers** [comment]
Planning to release 0.15.1 later this week with the merged fixes and dependency upgrades.

**Comment by jorisroovers** [comment]
I haven't forgotten but life got in the way... Still would like to do so soonish but no idea when I'll be able to make the time.

**Comment by gsemet** [comment]
I know that :) but if the current state is fine, why not releasing it as it is and then prepare a bigger maybe 0.17 ;)

**Comment by jorisroovers** [comment]
I'm not talking about adding more features or fixes, just about making the time (and mostly finding the energy/will after work and everything else) to get the release out. *Maybe* this weekend :)

**Comment by jorisroovers** [comment]
Just released 0.15.1 🎉  

Available on PyPi, other platforms usually take a bit to catch up

**Comment by harens** [comment]
All done on my side @jorisroovers 👍. Thanks for the new release.

MacPorts: https://github.com/macports/macports-ports/commit/6d3b7686c770d4ec8ab8a86493e6d956d6cfe8b9
Homebrew: https://github.com/Homebrew/homebrew-core/pull/75325 (credit to @dtrodrigues)
